name: Build Docker Image

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Env setup-java
      run: echo "DOCKER_VERSION=PR_$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')_${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Test
      run: echo $DOCKER_VERSION

    - name: Build and push Docker Image
      run: sbt stagePackage/docker:publish
      env:
        DOCKER_IMAGE_HOST: ghcr.io
        DOCKER_USERNAME: anhlt
        DOCKER_REPOSITORY: usermodule

        


